PropertyParser.java: PropertyLexer.g4  PropertyParser.g4
	java -jar ../antlr-4.7-complete.jar PropertyLexer.g4 PropertyParser.g4

clean:
	rm -f *.java *.class *.tokens

#test_run:
#	java -cp ".:../antlr-4.7-complete.jar" org.antlr.v4.gui.TestRig Property prog -gui
